-- 0006_idempotency.sql — the idempotency key protocol.
--
-- Forward-only (ADR-011).
--
-- # What this table is for
--
-- A client that retries a write — because a connection dropped, a proxy timed out, or
-- a user double-clicked — must not cause the effect twice. The standard mechanism is a
-- client-generated key: the first request with a given key executes and its response is
-- recorded; every later request with the same key returns that recorded response
-- without re-executing.
--
-- # Why the key is scoped to a tenant
--
-- The primary key is (tenant_id, key), not key alone. Two tenants choosing the same
-- key — and they will, because the natural choice is a UUID generated by a client
-- library that some clients will seed deterministically — must not collide: with a
-- global key, one tenant's request would replay another tenant's stored response,
-- which is both a correctness bug and a data leak.
--
-- Scoping also means the RLS policy below is a single tenant predicate, and a key can
-- never be claimed outside the tenant that owns it.

CREATE TABLE idempotency_keys (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

    -- Client-supplied. Length is bounded because the value arrives in a header and is
    -- stored: unbounded input would let a client fill the table with one request per
    -- megabyte of header.
    key text NOT NULL CHECK (length(key) BETWEEN 1 AND 255),

    -- SHA-256 of method, path, and body. It is what distinguishes "the same request
    -- again" (replay the stored response) from "a different request reusing this key"
    -- (refuse, because the client has a bug and replaying would answer the wrong
    -- question). Storing the hash rather than the request keeps credentials that appear
    -- in a body out of this table.
    fingerprint text NOT NULL CHECK (length(fingerprint) = 64),

    -- in_progress: claimed, handler running.
    -- completed:   the response is stored and replays.
    --
    -- There is deliberately no 'failed' state. A handler that returned an error has
    -- still *completed*: its status and body (the error envelope) are recorded and
    -- replayed, so a retry sees the same failure rather than re-running a write that
    -- may have partially applied. Treating a failure as "not done" is how a retry turns
    -- one failed write into two attempts at it.
    state text NOT NULL CHECK (state IN ('in_progress', 'completed')),

    -- The recorded response. Nullable while in_progress.
    status_code integer CHECK (status_code IS NULL OR (status_code BETWEEN 100 AND 599)),
    response_headers jsonb,
    response_body bytea,

    -- False when the response exceeded the storage cap. The key is still completed —
    -- its effect happened — but the body cannot be replayed, so a retry is answered
    -- with a conflict explaining that rather than with a truncated body that looks
    -- like a valid response.
    replayable boolean NOT NULL DEFAULT true,

    -- The principal that claimed the key, for attribution. Nullable because an
    -- internal caller may not have one.
    actor_id uuid,

    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,

    -- Retention boundary. A key is honoured for this long and then forgotten, after
    -- which the same value is a fresh request. The window has to exceed any realistic
    -- client retry schedule, because a client that retries after the key expires gets a
    -- second effect — which is the failure the table exists to prevent.
    expires_at timestamptz NOT NULL,

    PRIMARY KEY (tenant_id, key),

    -- A completed record must carry the response it promises to replay. Without this,
    -- a row could be marked completed with no status, and the replay path would have
    -- nothing to return — presenting as a 200 with an empty body rather than as an
    -- error.
    CONSTRAINT idempotency_completed_has_response CHECK (
        (state = 'in_progress' AND status_code IS NULL AND completed_at IS NULL)
        OR (state = 'completed' AND status_code IS NOT NULL AND completed_at IS NOT NULL)
    ),

    CONSTRAINT idempotency_expiry_after_creation CHECK (expires_at > created_at)
);

-- Sweeping expired rows is a range delete on expires_at; without this index it is a
-- sequential scan of every key ever issued.
CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (expires_at);

-- Finding the stale in-progress rows a crashed process left behind, which is the only
-- other query that scans rather than seeking a primary key.
CREATE INDEX idempotency_keys_in_progress_idx ON idempotency_keys (tenant_id, created_at)
    WHERE state = 'in_progress';

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Tenant-keyed, like projects: every request that reaches this table has a resolved
-- tenant, because an idempotency key is only meaningful for a tenant-scoped write. So
-- one predicate covers every operation, and the primary key's leading column matches
-- it exactly — the policy and the index agree, which is what keeps the check cheap.
-- ---------------------------------------------------------------------------
ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys FORCE  ROW LEVEL SECURITY;

CREATE POLICY idempotency_keys_tenant_isolation ON idempotency_keys
    FOR ALL
    USING (
        tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
    )
    WITH CHECK (
        tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
    );
